### ISSUE TITLE
Maintainership/help proposal

### ISSUE THREAD

**Issue by simonsan** [rust-unofficial/patterns#107]
Hi @lambda-fairy,

you stated [here](https://github.com/rust-unofficial/patterns/pull/100#issuecomment-703022335) that this repo needs some help, how do you imagine helping with this repository?
[MarcoIeni](https://github.com/MarcoIeni) & me would like to help. We could start reviewing all past issues and merging/closing or give some feedback to all pending PRs.

Long-term, we would also like to turn this repo into a `rust book` that can be served with GitHub pages to the community.

Cheers,
Simonsan & MarcoIeni

**Comment by lambda-fairy** [comment]
Thanks @simonsan and @Marcoleni!

I think your plan to clean up the backlog and make this into a book sounds good 🙁 

I don't have admin permissions, though, so I can't add you myself. Perhaps @nrc or @Manishearth can help here?

**Comment by Manishearth** [comment]
@lambda-fairy gave you admin, feel free to make changes to perms

**Comment by lambda-fairy** [comment]
Thanks Manish!

@simonsan and @MarcoIeni I have invited both of you. Please let me know if it works!

**Comment by simonsan** [comment]
> @simonsan and @MarcoIeni I have invited both of you. Please let me know if it works!

Works. :-)

**Comment by MarcoIeni** [comment]
Thanks, I will do my best! :)

**Comment by simonsan** [comment]
@lambda-fairy Could you take a look if we need extra permissions to convert `issues` into `discussions`? Because I don't see this option here:
https://docs.github.com/en/free-pro-team@latest/discussions/managing-discussions-for-your-community/managing-discussions-in-your-repository#converting-issues-based-on-labels

**Comment by lambda-fairy** [comment]
All of us have an "Admin" role, which is the highest level of access available. So I don't know what else I can do.

https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization

**Comment by simonsan** [comment]
> All of us have an "Admin" role, which is the highest level of access available. So I don't know what else I can do.
> 
> https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization

Ok, thank you for looking into this. I'll need to investigate on it further then. I wish you a happy new year. :-) 🎉

**Comment by simonsan** [comment]
https://docs.github.com/en/free-pro-team@latest/discussions/managing-discussions-for-your-community/moderating-discussions#converting-an-issue-to-a-discussion

Maybe this is only possible for issues that are made after activating discussions or something else giving the fact that it's still in a beta. We'll see.
