### ISSUE TITLE
Address issues from the reddit thread

### ISSUE THREAD

**Issue by nrc** [rust-unofficial/patterns#11]
https://www.reddit.com/r/rust/comments/3ptlgq/design_patterns_in_rust_blog_post/

**Comment by simonsan** [comment]
Big topic, we need to work through that thread and check against already existing issues/PRs and the status quo of the content.

**Comment by simonsan** [comment]
I read through it and haven't really found anything that would be worth opening with, also it's really old (5 years) and probably makes sense to cut it at this point. Closing this now. ;-)
