### ISSUE TITLE
Add markdown linter in CI

### ISSUE THREAD

**Issue by MarcoIeni** [rust-unofficial/patterns#119]
It would be nice to have something in CI that tells us if markdown is correct.
For example this markdown is not valid:

```
# section 1

### section 2
```

Or stuff like: avoid tabs or detect trailing whitespaces.

**Comment by simonsan** [comment]
We could use this action for linting
https://github.com/marketplace/actions/markdownlint-mdl-action

Not sure how complicated it is though to find a "style" that fits but at least tabs, whitespaces and the section headers should be easily setup.

**Comment by MarcoIeni** [comment]
Other ones I've found:
- https://github.com/logansquirel/action-markdownlint
- https://github.com/ruzickap/action-my-markdown-linter
- https://github.com/avto-dev/markdown-lint
- https://github.com/gaurav-nelson/github-action-markdown-link-check

**Comment by MarcoIeni** [comment]
We have to choose between:
- The action simonsan suggested - uses https://github.com/markdownlint/markdownlint
- https://github.com/avto-dev/markdown-lint - uses https://github.com/DavidAnson/markdownlint

Thanks to the parameter "number of stars" the second option is winning at the moment :joy: 
Do you have any preference?

**Comment by simonsan** [comment]
>     * https://github.com/avto-dev/markdown-lint - uses https://github.com/DavidAnson/markdownlint

Seems better maintained and has the better documentation and tooling (e.g. [VScodium](https://vscodium.com/) extension) it seems

**Comment by MarcoIeni** [comment]
Nice, let's use that one.
Who wants to start working on this can leave a comment here.

**Comment by Takashiidobe** [comment]
I'd like to work on this:

I propose doing a few things:

- Running markdownlint on all markdown files in the project:
- Then setting up the the github action to check for markdown lint errors on PR.

**Comment by simonsan** [comment]
> I'd like to work on this:
> 
> I propose doing a few things:
> 
>     * Running markdownlint on all markdown files in the project:
> 
>     * Then setting up the the github action to check for markdown lint errors on PR.

Nice!
