### ISSUE TITLE
Strategy design pattern

### ISSUE THREAD

**Issue by fade2black** [rust-unofficial/patterns#120]
Working on https://medium.com/swlh/strategy-design-pattern-in-rust-5f5486cd294c?source=friends_link&sk=6871f4761dc6c4b7c0bc3ccefd22e408

**Comment by NilSet** [comment]
The blog post uses dynamic dispatch without any apparent need. The article in the book should probably cover the tradeoffs of using generics vs using dynamic dispatch.

**Comment by fade2black** [comment]
@NilSet  How about removing it (dispatch version) completely?

**Comment by fade2black** [comment]
@NilSet  [Here](https://github.com/fade2black/patterns/blob/master/patterns/strategy.md) I provide a version with static dispatch.

**Comment by simonsan** [comment]
Linked it to the PR, let's keep it open until we actually merge it. Maybe there is still some feedback from @pickfire and I'll also read through it the upcoming days. Cheers.
