### ISSUE TITLE
In-repo links not working on mdBook

### ISSUE THREAD

**Issue by simonsan** [rust-unofficial/patterns#130]
Currently in repository links to other md files (e.g. in intro (and other pages?)) are not working due to https://github.com/rust-lang/mdBook/issues/431

**Comment by simonsan** [comment]
I've added direct links now to `intro.md` to the book chapters. That's obviously no long-term solution. :-/

**Comment by MarcoIeni** [comment]
Attempt to fix this in #143

> Other in-repo links are still broken inside the book.

If that solution works, we can apply it also to the other links

**Comment by simonsan** [comment]
> If that solution works, we can apply it also to the other links

The other in-repo links mysteriously work 🤷🏽, not sure, but we could be also able to solve it if we rename the README.md to index.md? Might be worth a try

**Comment by MarcoIeni** [comment]
Is this solved now?
If not can you provide not working links or submit a PR to fix them?

**Comment by simonsan** [comment]
👍🏽
