### ISSUE TITLE
Make the display of a new chapter more clear to the reader

### ISSUE THREAD

**Issue by simonsan** [rust-unofficial/patterns#141]
> when walking the chapters using the next button, I initially thought the Functional Programming chapter was part of the anti-patterns chapter and was confused why FP was an anti-pattern.

src.: [reddit](https://www.reddit.com/r/rust/comments/kowtqn/rust_design_patterns_now_also_as_a_book/ghvvj0s/?utm_source=reddit&utm_medium=web2x&context=3)

**Comment by MarcoIeni** [comment]
We can have a smaller intro and then put the discussion imperative vs declative in another page.
