### ISSUE TITLE
Add markdown linter offline usage to CONTRIBUTING

### ISSUE THREAD

**Issue by simonsan** [rust-unofficial/patterns#167]
Due to #164 we are now checking markdown style in PRs. To make it easier for people to contribute, we should also document in CONTRIBUTING.md how people can actually install, lint offline and apply the fixes automatically.

```
npm install -g markdownlint-cli
markdownlint -f **/*.md
markdownlint -f *.md
```

**Comment by MarcoIeni** [comment]
I am not it.
