### ISSUE TITLE
Cut long lines

### ISSUE THREAD

**Issue by MarcoIeni** [rust-unofficial/patterns#185]
In [this](https://github.com/rust-unofficial/patterns/blob/master/.markdownlint.yaml) file we set the maximum line length for our markdown linter.
Our end goal is to bring it to something sane, like 150 for example.
Right now it is 300.

You should edit that file in order to decrease the number a little bit and fix all the errors that are showed by running `markdownlint` as explained in [CONTRIBUTING](https://github.com/rust-unofficial/patterns/blob/master/CONTRIBUTING.md#markdown-lint).

Try to keep PR small, i.e. do not set that number to 150 directly and fix hundreds of lines at the same time.
Fixing around 10 lines per PR might be a good number for example, so you can set it to 230 for the first iteration for example.

You can see [this](https://github.com/rust-unofficial/patterns/pull/176) PR as an example.
If you want to work on this leave a comment and we will assign the issue to you.
You can also do just one single PR, that's fine, you don't have to do all the job. Just specify that in the comment :)

**Comment by simonsan** [comment]
I actually think to have it done sooner than later is better, as it enables us (or git) to track changes more easily with shorter sentences. I'll did it already with 150 line length will make a PR.

**Comment by simonsan** [comment]
Was also really not that big, bit more than hundred lines and to have it in one PR is imho also better than clutter the history with 20 PRs that change a small amount. Like this we have one PR with one consistent change.

**Comment by simonsan** [comment]
What about cutting them down to 80 as mentioned in the style guide? I personally use 80 as well for coding.

**Comment by MarcoIeni** [comment]
For me it's ok!
However, let's keep cargo fmt default for rust code. 80 characters only for markdown text.

As I said in the first post, let's try to keep PRs small, so let's do something 130 -> 110 -> .. and so on

**Comment by simonsan** [comment]
> As I said in the first post, let's try to keep PRs small, so let's do something 130 -> 110 -> .. and so on

Wouldn't do that honestly. Think it's too many PRs for the same thing. Think one PR with line length 80. Is fine, what is the advantage of making it in smaller pieces but 10-20 PRs for it?

**Comment by MarcoIeni** [comment]
It would be easier to review and can be done by different people.
Anyway if you want to do this and you prefer to do it all at once it is fine.
