### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by cbreeden** [rust-unofficial/patterns#26]
Hi @nrc 

It appears that there hasn't been much activity for this effort recently.  I think this kind of information is quite valuable, and we should pass the torch to a new maintainer.  I would  gladly take responsibility for maintaining this project -- recently I was working on what I wanted to call the Rust Cookbook, and this seems to be right up the same ally.  Also, I'm sure there are others who are perfectly capable and may be willing; @lfairy comes to mind.

Let me know!

**Comment by lfairy** [comment]
If being a maintainer involves just proof-reading contributions, then I'd be up for that.

**Comment by cbreeden** [comment]
Personally I'd like to see some like this in a community spot where we could have a few

**Comment by cbreeden** [comment]
Sorry phones are hard.

**Comment by nrc** [comment]
Hey, thanks for the interest in this! I'd love to have more help. Moving the repo somewhere with more community visibility sounds like a good idea too. I'm currently at Rustconf and then will be travelling home, but I'll email you both or talk to you on irc about the best way to move forward early next week.

**Comment by nrc** [comment]
Hi all, I talked to the community team and they thought that https://github.com/rust-unofficial would be the best home for this repo (and possibly moving somewhere more official and discoverable if/when it matures).

I'd be happy to then setup an 'editors' team of people with merge access to maintain the repo and merge new contributions.

@cbreeden, @lfairy does that sound like a good plan to you? Anything you'd rather do? Like to add?

**Comment by cbreeden** [comment]
> https://github.com/rust-unofficial would be the best home for this repo (and possibly moving somewhere more official and discoverable if/when it matures).

Great idea!  I also have an idea to possibly help kick off a little of the rust: perhaps we can place an ad in TWiR under the request for participation after the migration.  If you are need some man power for editing, I'd certainly volunteer and I think I know someone else who may also be interested, but I would have to ask them first.

**Comment by lfairy** [comment]
@nrc that sounds great! I second @cbreeden's suggestion to advertise in TWiR, but don't have anything else to add.

**Comment by nrc** [comment]
So, the repo is transferred and you should both be added as collaborators meaning you have push/merge access. I think it would be best to still get review on contributions (other than trivial stuff).

Could one of you contact TWiR to advertise the change please?

**Comment by lfairy** [comment]
> Could one of you contact TWiR to advertise the change please?

I've filed an issue at cmr/this-week-in-rust#313.
