### ISSUE TITLE
Using `&str` vs using `&String`

### ISSUE THREAD

**Issue by cbreeden** [rust-unofficial/patterns#27]
This is a common idiom, where using an `&str` is often more flexible than using a `&String`.

**Comment by MarcoIeni** [comment]
Same is true for Path and PathBuf I believe, and also for Vec and slices.
There is also a clippy lint about this (works only with nightly): https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
We should express this concept in a general way and add it to idioms.

**Comment by simonsan** [comment]
This issue should be fixed with #29 I believe, if not feel free to reopen.
