### ISSUE TITLE
example in the section 'Clone to stasify borrow checker' may deprecated due to NLL

### ISSUE THREAD

**Issue by poly000** [rust-unofficial/patterns#290]
```rust
// define any variable
let mut x = 5;
// Borrow `x` -- but clone it first
let y = &mut (x.clone());
// perform some action on the borrow to prevent rust from optimizing this
//out of existence
*y += 1;
// without the x.clone() two lines prior, this line would fail on compile as
// x has been borrowed
// thanks to x.clone(), x was never borrowed, and this line will run.
println!("{}", x);
```

the `println!` could work due to NLL even if there is no `clone()` call, to solve this, `*y += 1;` should be placed under `println!`, so at the println line, y lives

**Comment by pickfire** [comment]
Deperated?

**Comment by poly000** [comment]
> Deperated

Sorry , I mean, deprecated

**Comment by sollyucko** [comment]
Wouldn't the behavior be different, printing 5 with `clone` and 6 without?

**Comment by poly000** [comment]
> Wouldn't the behavior be different, printing 5 with `clone` and 6 without?

behavior will not change, so actually only the line ` // thanks to x.clone(), x was never borrowed, and this line will run.` needs change
