### ISSUE TITLE
Translation: Newer simplified Chinese

### ISSUE THREAD

**Issue by Fomalhauthmj** [rust-unofficial/patterns#292]
In last two weeks, I read this book and did my best to translate it into a newer simplified Chinese translation.
Maybe we can add a translation list in readme for those who want read in native language?.🤔
The translation repo is [here](https://github.com/Fomalhauthmj/patterns) .

**Comment by simonsan** [comment]
As long as mdbook doesn't support [i18n](https://github.com/rust-lang/mdBook/issues/5) we should probably create a new sections for 'translations' in `SUMMARY.md` and collect them there.

**Comment by pickfire** [comment]
@Fomalhauthmj I think can just use the usual approach when i18n is not support, put the translated link in README.

**Comment by Fomalhauthmj** [comment]
Of course, I will review my translation again in the spare time for a better reading experience.

**Comment by Fomalhauthmj** [comment]
Ok, I have learned how to work with po files.When my translation being prepared, I will open a pr on main branch.

**Comment by Fomalhauthmj** [comment]
@simonsan , I found that `messages.pot` file doesn't contain corresponding quote links, check [this file](https://github.com/rust-unofficial/patterns/blob/main/src/idioms/ctor.md?plain=1), the following contents can't found in `messages.pot`.
```markdown
[associated function]: https://doc.rust-lang.org/stable/book/ch05-03-method-syntax.html#associated-functions
[std-default]: https://doc.rust-lang.org/stable/std/default/trait.Default.html
[std-or-default]: https://doc.rust-lang.org/stable/std/?search=or_default
[API Guidelines/C-COMMON-TRAITS]: https://rust-lang.github.io/api-guidelines/interoperability.html#types-eagerly-implement-common-traits-c-common-traits
```

**Comment by Fomalhauthmj** [comment]
I have checked the process of `create_catalog` in [mdbook-i18n-helpers](https://github.com/google/mdbook-i18n-helpers), use following test function:
```rust
    fn my_test() -> anyhow::Result<()> {
        let (ctx, _tmp) = create_render_context(&[
            ("book.toml", "[book]"),
            ("src/SUMMARY.md", "- [The Foo Chapter](foo.md)"),
            (
                "src/foo.md",
                "this is a quota link [name1][ref1].\n\n[ref1]:test_url\n",
            ),
        ])?;

        let catalog = create_catalog(&ctx)?;

        for msg in catalog.messages() {
            assert!(!msg.is_translated());
        }
        Ok(())
    }
```
And，the events we got are:
```
Start(Paragraph) -- "this is a quota link [name1][ref1].\n"
Text(Borrowed("this is a quota link ")) -- "this is a quota link "
Start(Link(Reference, Borrowed("test_url"), Borrowed(""))) -- "[name1][ref1]"
Text(Borrowed("name1")) -- "name1"
End(Link(Reference, Borrowed("test_url"), Borrowed(""))) -- "[name1][ref1]"
Text(Borrowed(".")) -- "."
End(Paragraph) -- "this is a quota link [name1][ref1].\n"
```
It seems like that we need make sure that `[ref1]` shouldn't be translated for correct reference-style links. In this way, the reference-style links can work fine as usual.
