### ISSUE TITLE
Translate: Vietnamese

### ISSUE THREAD

**Issue by TropicalDog17** [rust-unofficial/patterns#372]
Hello, I'd like to contribute a Vietnamese translation to the project.
Please inform me of the next steps to get started. Thank you!

**Comment by simonsan** [comment]
(I reopened, because also if you don't want to do the Vietnamese translation, others might want to, when we finished setting up the translation pipeline, so don't feel obligated to still keep that offer up ;) )

**Comment by TropicalDog17** [comment]
Hi so what's status of the translation pipeline setup? @simonsan

**Comment by simonsan** [comment]
> Hi so what's status of the translation pipeline setup? @simonsan

I'm currently working on `rustic` a bit, but still have the intention, to finish the translation pipeline. I need to read myself in again, on the current state of it. It's on my roadmap for this year, so hoping to get it done before January!

**Comment by TropicalDog17** [comment]
@simonsan Would love to have a follow up on this issue. With development of LLM-assisted programming, do you think the translation pipeline(if still not completed) will be finalized for this repo?
