### ISSUE TITLE
Make "mem::replace to keep owned values in changed enums" example more general

### ISSUE THREAD

**Issue by briansmith** [rust-unofficial/patterns#38]
The example seems unrealistic because it uses `if let` instead of `match`. The example should use `match` since it is more general. Most of the cases where I would use this pattern would require the use of `match`.

**Comment by cbreeden** [comment]
Hmm, I tend to agree.  The original PR used a `match` and then another PR simplified this particular example (and probably correctly so) to an `if let`.  Perhaps it may be worthwhile to finding an example out in the wild unless someone else has another example in mind?

**Comment by diwic** [comment]
I use `if let` much more often than `match`.

**Comment by nrc** [comment]
I don't we can say `match` or `if let` is more general or more common, but as a matter of style I think that example should use `match` - where you have where there is both an `if let` and an `else` branch, it is nearly always better to use `match`.

**Comment by briansmith** [comment]
Maybe it's good to have two examples, one with `if let` and one with `match`. Then we can direct people to the specific example that most closely matches their code.
