### ISSUE TITLE
Rreturning a guard, c.f. `JoinGuard` and `MutexGuard`

### ISSUE THREAD

**Issue by timClicks** [rust-unofficial/patterns#42]
Just an idea, would "Guard" count as a pattern?

Although `sys::thread::scoped` is unstable, `sys::sync::MutexGuard` is alive and well. Returning a guard object seems like an interesting way to make sure that an object can outlive past the curreny scope, by allowing the guard to be dropped and acting upon the referent (e.g. unlocking the `Mutex`).

A fairly terse description: Returning a proxy type with an inner reference to the original, that incorporates `#[must_use]` attribute and a probably reference to `poison::Guard`. Returning the guard can allow referents to outlive the calling scope and yet can still be acted upon when the scope changes. 

(Apologies if this is already written up or doesn't count! Maybe it's too narrow if it's only used for implementing concurrency primitives?)

**Comment by nrc** [comment]
This is covered by https://github.com/rust-unofficial/patterns/blob/master/patterns/RAII.md I think

**Comment by timClicks** [comment]
Ah yup, oops.
