### ISSUE TITLE
rustdoc --test the examples

### ISSUE THREAD

**Issue by llogiq** [rust-unofficial/patterns#49]
I have a local branch here that does this. Obviously some examples are not meant to run (e.g. partial copies from `std`), those can be marked with `ignore`.

Otherwise examples should run if it doesn't make them unreadable. I consider adding one or two lines of `use` declarations acceptable.

Thoughts?

**Comment by lfairy** [comment]
Good idea! I'd be keen for that, as long as new contributors are made aware of it.

**Comment by cbreeden** [comment]
I like it.  It also may nudge us a little bit to make complete examples, which I'm in favor for.

**Comment by llogiq** [comment]
We can add a small sentence to the README. Also using Travis to check PRs will make it pretty obvious.

**Comment by simonsan** [comment]
We're using `mdbook` now to build the book and have CI running on PRs and pushes to master, so I'm closing this as this should catch these cases.
