### ISSUE TITLE
Convert this to a gitbook/mdbook

### ISSUE THREAD

**Issue by dumindu** [rust-unofficial/patterns#6]
Hi,
Thanks for sharing. This will be more readable if you can create a gitbook with this :)

**Comment by killercup** [comment]
I agree. Gitbook's structure also works with https://github.com/steveklabnik/rustbook

**Comment by mkpankov** [comment]
Please note that Gitbook will choke on Rust's doctests or some other parts that require embedded markdown.

That's not a problem if you don't plan to use these features in this project.

**Comment by vinipsmaker** [comment]
> more readable

And ePUB support is always appreciated (comes for free once you use gitbook).

> I agree. Gitbook's structure also works with https://github.com/steveklabnik/rustbook

Does rustbook support ePUB and PDF output like gitbook?

**Comment by DaseinPhaos** [comment]
I'm not pretty sure where this is going but how about converting to mdbook?
