### ISSUE TITLE
Pattern for writing rustdoc examples without initialization 

### ISSUE THREAD

**Issue by tkaitchuck** [rust-unofficial/patterns#91]
If you have a type Foo that has some complex initialization that you don't really want to inline into each example for every method on Foo, you can instead do:

```
/// bar is an important method on Foo. It does things.
/// #Example
/// ```
/// # fn call_bar(foo: &Foo) {
/// let value = foo.bar();
/// # }
/// ```
fn bar(&self) -> u32 {
//...
}
```
This avoids having to type several lines of logic to initialize `foo` in a concise way without having to jump to doing a "```ignore".

**Comment by pickfire** [comment]
Ah, I didn't know this works. Interested to send a patch for this?

**Comment by tkaitchuck** [comment]
https://github.com/rust-unofficial/patterns/pull/97

**Comment by simonsan** [comment]
Should be fixed. Closing.
